geultto/daily-solvetto

ChoYoonU/javascript/120814.js

- 문제: [120814번: 피자 나눠 먹기(1)](https://school.programmers.co.kr/learn/courses/30/lessons/120814)
- 플랫폼: 프로그래머스
- 언어: js
✅ 해결  🟩 미해결  🟩 포기
풀이에 걸린 시간: 10분
🟩 문제를 읽고 주어진 시간제한과 메모리제한 내에서의 풀이가 떠올랐다.
✅ 문제를 읽고 시간제한과 메모리제한 내에서 해결이 가능한 지는 모르겠지만 풀이가 떠올랐다.
🟩 문제를 읽고 풀이가 떠오르지 않았다.
🟩 문제가 곧바로 이해되지 않았다.
✅ 풀이를 아무런 도움 없이 작성하였다.
🟩 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.
🟩 풀이를 남의 정답코드를 찾아 참고하여 작성하였다.
🟩 알고리즘 개념에 대한 공부를 하다 해당 개념에 대한 문제를 찾았고, 풀었다.
- Math.ceil(올림 함수)
1. 나눗셈을 통해 필요한 피자 판 계산
- n명을 7로 나누어 피자 판 수를 계산합니다.
- 이때, 딱 떨어지지 않는 경우를 고려해 올림(Math.ceil)을 사용합니다.

# 프로그래머스 #120814

---

Kyungmin_Choi/Swift/WordOccursAsAPrefix.swift

- 문제: [LeetCode No.1455 Check If a Word Occurs As a Prefix of Any Word in a Sentence](https://leetcode.com/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/)
- 언어: Swift
✅ 해결  🟩 미해결  🟩 포기
풀이에 걸린 시간: 3분
✅ 문제를 읽고 주어진 시간제한과 메모리제한 내에서의 풀이가 떠올랐다.
🟩 문제를 읽고 시간제한과 메모리제한 내에서 해결이 가능한 지는 모르겠지만 풀이가 떠올랐다.
🟩 문제를 읽고 풀이가 떠오르지 않았다.
🟩 문제가 곧바로 이해되지 않았다.
✅ 풀이를 아무런 도움 없이 작성하였다.
🟩 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.
🟩 풀이를 남의 정답코드를 찾아 참고하여 작성하였다.
🟩 알고리즘 개념에 대한 공부를 하다 해당 개념에 대한 문제를 찾았고, 풀었다.
- 배열 순회
- Early Return
- LeetCode 오늘의 문제
- Swift 내장 메서드 `hasPrefix`를 통해 어떤 `String`이 다른 `String`의 접두어인지 알 수 있다는 사실을 숙지했다.
- `components` 내장 메서드를 활용해 공백을 기준으로 단어별로 문장을 쪼개어 배열로 만들었다.
- 이후 해당 배열을 순회하며 키워드가 단어에 들어 있는지 확인하고, 만약 들어 있다면 해당 부분의 1-index를 반환하게 했다.
- 순회가 끝나도 매칭되는 단어가 없다면 조건에 부합하는 단어가 …

1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence

---

SimDongMin/java/SearchInRotatedSortedArray.java

- 문제: [33번 Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/description/)
- 플랫폼: 리트코드
- 언어: java
- 풀이에 걸린 시간: 40분
- 풀이가 떠오른 과정: 문제를 읽고 풀이가 떠오르지 않았다.
- 풀이 작성 과정: 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.
- 중간 지점을 기준으로 왼쪽이든 오른쪽이든 하나는 정렬이 되어있음을 이용. 
- binary search에서 조건을 추가해 풀이.
- 왼쪽, 오른쪽 중 정렬되어있는 부분 찾기.
- 정렬되어있는 범위에 target값이 존재하는지 확인.
- 없음

LeetCode #33

---

KimJuWon/python/트로미노.py

- 문제: [트로미노](https://www.codetree.ai/missions/2/problems/tromino?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 32분 18초
- 풀이 작성 과정: 아무런 도움없이 혼자 풀어냈다.
- 완전 탐색 문제
- 완전탐색 문제임으로 격자 모형이 가능한 경우의 수를 생각하는 것이 핵심이라고 생각하며 문제를 접근하였다. Index Out of Boundaries에러가 나지 않도록 정리하는 것이 핵심

코드트리 #트리미노

---

Geunho/Python/LeetCode_2109.py

- 문제: [2109번: Adding Spaces to a String](https://leetcode.com/problems/adding-spaces-to-a-string)
- 언어: Python
- 풀이에 걸린 시간: 5분
- 풀이가 떠오른 과정: 전형적인 구현 문제라 예제 입출력을 보고 바로 구현 시작
- 풀이 작성 과정: 예제 입출력에 대해서 테스트 케이스 검증 후 풀이

LeetCode #2109

---

KimJuWon/python/금 채굴하기.py
KimJuWon/python/트로미노.py

- 문제: [금채굴하기](https://www.codetree.ai/missions/2/problems/gold-mining?&utm_source=clipboard&utm_medium=text)
- 플랫폼: 코드트리
- 언어: python
- 완전 탐색 문제 
- 주어진 격자내에서 마름모를 k의 크기에 맞게 그려나가며, 마름모 안에서 획득할 수 있는 최대 금의 갯수를 찾는 것이 핵심 
- 마름모가 격자의 크기보다 커질 수 있지만, 비용이 늘어나는 Trade-off관계를 생각하여 가짓수를 나눠 알고리즘을 짜야함

코드트리 #금채굴하기

---

ChoYoonU/javascript/120815.js
ChoYoonU/javascript/120816.js

- 문제: [120816번: 피자 나눠 먹기(3)](https://school.programmers.co.kr/learn/courses/30/lessons/120816)
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 30분
- 풀이 작성 과정:  풀이를 아무런 도움 없이 작성하였다.
- n을 slice로 나누었을 때 몫을 올림(Math.ceil(n / slice))하여 필요한 피자 판 수를 구합니다.

프로그래머스 #120816.피자 나눠 먹기(3)

---

ParkJiHan/python/14003.py

- 문제: [14003번: 가장 긴 증가하는 부분 순열 5](https://www.acmicpc.net/problem/14003)
- 플랫폼: 백준
- 언어: python
✅ 해결  🟩 미해결  🟩 포기
풀이에 걸린 시간: 1시간 ~ 2시간
🟩 문제를 읽고 주어진 시간제한과 메모리제한 내에서의 풀이가 떠올랐다.
✅ 문제를 읽고 시간제한과 메모리제한 내에서 해결이 가능한 지는 모르겠지만 풀이가 떠올랐다.
🟩 문제를 읽고 풀이가 떠오르지 않았다.
🟩 문제가 곧바로 이해되지 않았다.
✅ 풀이를 아무런 도움 없이 작성하였다.
🟩 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.
🟩 풀이를 남의 정답코드를 찾아 참고하여 작성하였다.
🟩 알고리즘 개념에 대한 공부를 하다 해당 개념에 대한 문제를 찾았고, 풀었다.
- 이진탐색(Binary Search)
- 다이나믹 프로그래밍(Dynamic Programming)
1. DP로 시간복잡도 줄이기( $O(2^N) => O(N^2)$ )
- 모든 부분 순열을 구해서 증가와 최장 여부를 직접 확인하는 방식에서 증가와 최장 여부를 구하는 부분을 메모이제이션하여 DP로 풀이함으로써 시간복잡도를 줄였습니다.
2. 이진탐색으로 선형탐색 대체하여 시간복잡도 줄이기( $O(N^2) => O(NlogN)$ )
3. DP로 최적해를 구할 때 바로 직전 점화식에서의 인덱스를 함께 저장하도록 해서 마지막에 구한 LIS에서 역추적을 통해 LIS를 복구할 수 있도록 함.

백준 14003.가장 긴 증가하는 부분 순열 5

---

ChoiSoYeong/javascript/42579.js
ChoiSoYeong/javascript/92334.js

- 문제: [42579번: 베스트앨범](https://school.programmers.co.kr/learn/courses/30/lessons/42579)
- 플랫폼: 프로그래머스
- 풀이가 떠오른 과정: 문제를 읽고 풀이가 떠오르지 않았다.
- 풀이 작성 과정: 풀이를 남의 정답코드를 찾아 참고하여 작성하였다.
1. 장르별 총 재생 횟수와 각 곡의 재생 횟수를 저장하는 객체를 선언해, 데이터를 저장한다.
2. 총 재생횟수가 많은 장르 순으로 정렬한다.
3. 각 장르 내에세 노래를 재생 횟수 순으로 정렬해 최대 2곡까지 선택한다.
다른 풀이 방법이 있는지 궁금합니다.

programmers #42579

---

ChoYoonU/javascript/120818.js

- 문제: 120818번: 옷가게 할인 받기
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 35분
- 가격이 50만 원 이상일 때 20% 할인 (price * 0.8),
- 가격이 30만 원 이상일 때 10% 할인 (price * 0.9),
- 가격이 10만 원 이상일 때 5% 할인 (price * 0.95)
- 할인된 금액을 버림(Math.floor())하여 소수점을 제거한 뒤 반환합니다.
- 처음에는 코드 실행을 했을때는 맞았으나 제출 후 채점하기 눌렀을 때는 틀렸습니다라고 나왔었습니다.
- 다시 코드를 확인을 해보니 조건들에 해당하지 않을 때 조건이 없어서였습니다.

프로그래머스 #120818.옷가게 할인 받기

---

Geunho/Python/BOJ_1158.py

- 문제: [1158번: 요세푸스 문제](https://www.acmicpc.net/problem/1158)
- 플랫폼: 백준 온라인 저지
- 언어: Python
- 풀이에 걸린 시간: 15분
- 풀이가 떠오른 과정: 환형 연결리스트 구현 후 조건에 맞게 노드 하나씩 제거하면서 남은 노드 연결
- 풀이 작성 과정: 1) 환형 연결리스트 구현 2) 모든 노드 제거하는 로직 구현 3) 정답 출력

Solve a problem on 7th Dec

---

ChoYoonU/javascript/120819.js

- 문제: 120819번: 아이스 아메리카노
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 36분
- 한 잔 가격(oneMoney = 5500)을 기준으로, 최대 잔 수는 몫(Math.trunc(money / oneMoney)으로 계산합니다.
- 남는 돈은 나머지(money % oneMoney)로 계산합니다.
- 결과를 배열에 담아 반환합니다.

프로그래머스 #120819.아이스 아메리카노

---

Geunho/Python/LeetCode_2054.py

- 문제: [2054번: Two Best Non-Overlapping Events](https://leetcode.com/problems/two-best-non-overlapping-events)
- 언어: Python
- 풀이에 걸린 시간: 1시간
- 풀이가 떠오른 과정: 그리디 방식으로 처음에 접근했으나, 단일 이벤트 or 최대 2개의 Event만 고려하면 되므로 정렬 후 조건에 맞는 이벤트들만 우선순위 큐를 이용해서 뽑으면 풀이 가능 캐치
- 풀이 작성 과정: 그리디 / 투포인터 등 접근하다가 우선순위 큐 방식으로 선회

LeetCode #2054

---

KimJuWon/python/겹쳐지지 않는 두 직사각형.py

- 문제: [겹치지 않는 직사각형](https://www.codetree.ai/missions/2/problems/non-overlapping-two-rectangles?&utm_source=clipboard&utm_medium=text)
- 플랫폼: 코드트리
- 언어: python
- 풀이에 걸린 시간: 41분
- 유형 : 완전탐색 유형 
- 풀이 키워드 : 격자내에 겹치지 않는 직사각형을 모두 그려, 두 직사각형 격자내부의 수의 합이 최대가 하게 되는 경우를 구해야합니다. 
- BigO시간 : n,m은 5이하의 수로 O(nm^5)이하로 풀이를 구해야했으며, O(nm^5)이하가 되도록 루프문을 구현하여 코드를 구현하였습니다.

# 코드트리 # 겹치지 않는 직사각형

---

ChoYoonU/javascript/120820.js

- 문제: 120820: 나이 출력
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 5분
- 현재 연도(2022년)에서 주어진 나이(age)를 뺀 뒤, 1을 더해 출생 연도를 계산합니다.

프로그래머스 #120820.나이 출력

---

Sanghee/javascript/최댓값과 최솟값.js

- 문제: [최댓값과 최솟값](https://school.programmers.co.kr/learn/courses/30/lessons/12939)
- 플랫폼: 프로그래머스
- 풀이에 걸린 시간: 5분
문자열에서 공백 기준으로 split하고 숫자 배열을 만들어서, Math 메서드로 최댓값, 최솟값을 가져오도록 했다.

solve: 최댓값과 최솟값 (프로그래머스 lv2)

---

KimJuWon/python/양수 직사각형의 최대 크기.py

- 문제: [양수 직사각형의 최대 크기](https://www.codetree.ai/missions/2/problems/max-area-of-positive-rectangle?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 21분 30초
- 문제 유형 : 완전 탐색 문제 
- Big-O시간 : 해당 문제는 행과 열의 길이가 각각 20이하의 수(n,m)이고, 1초이내에 문제를 해결해야하므로 O(nm^3)이하 정도의 시간 복잡도를 가지면 풀 수 있을 것이라고 생각했습니다. 
- 문제 풀이 방법 : 직사각형 내부의 그리드가 모두 양수여야 하므로, 주어진 범위(n, m) 내에서 가능한 모든 네 개의 꼭짓점을 완전 탐색합니다. 각 경우에 대해 직사각형 내부가 모두 양수인지 확인하고, 조건을 만족하면 직사각형의 크기를 계산해 최대 크기를 갱신하는 방식으로 코드를 작성했습니다.

# 코드 트리 # 양수 직사각형의 최대 크기

---

ChoYoonU/javascript/120821.js

- 문제: 120820: 나이 출력
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 2분
- num_list 배열에 대해 reverse() 메서드를 사용하여 배열의 순서를 뒤집었으며 이를 answer에 저장하여 반환하였습니다.

프로그래머스 #120821.배열 뒤집기

---

KimJuWon/python/컨베이어 벨트.py

- 문제: [컨베이어 벨트](https://www.codetree.ai/missions/2/problems/conveyor-belt?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 12분 14초
- 유형 : 완전탐색
- BigO 제한 시간 : 컨베이어 벨트의 길이 2 * n 으로 최대 200까지 가능하고, 움직이는 시간 t는 1000이하이다. 이 문제에서는 t초 동안 움직이는것이 핵심이므로 O(t^2logt)안에 문제를 해결하기만 하면 된다. 
- 구현 방법 : 2개의 deque으로 이루어진 컨베이어 벨트를 선언하고, t초마다 각 앞/끝점에서 pop/append가 되도록 구현하여 주면, 해당 문제는 O(t)가 되는 시간 복잡도를 가진 알고리즘을 통해 구현해줄 수 있다.

# 코드 트리 # 컨베이어 벨트

---

KimJuWon/python/삼각형 컨베이어 벨트.py

- 문제: [삼각형 컨베이어 벨트](https://www.codetree.ai/missions/2/problems/conveyor-belt-triangle?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 14분 45초
- 유형 : 완전탐색
- Big-O시간 : 삼각형 컨베이어 벨트에 있는 원소들이 하나씩 밀려가므로, 삼각형 컨베이어 벨트의 크기(3n)와 주어진 시간 t초를 고려하여 최대 O(n^2t)또는 O(nt^2)안에 문제를 풀어야 한다. 
- 컨베이어 벨트의 시뮬레이션을 이차원 리스트를 이용해서 순차적으로 원소를 움직이고, t초 후의 모습을 출력해주는 문제이다. 따라서, 시뮬레이션을 돌려 컨베이어 벨트의 길이(3n) * 움직인 시간(t)초만큼 시간이 걸리는 O(nt)의 빅오시간을 갖는 코드로 구현해주었다. 
- 더 나은 방법 : t초 후의 인덱스를 계산해서 구할 수도 있다. 이 경우 비약적으로 시간복잡도가 감소한다.(상수시간)

# 코드트리 # 삼각형 컨베이어 벨트

---

Sanghee/javascript/로또의 최고 순위와 최저 순위.js

- 문제: [로또의 최고 순위와 최저 순위](https://school.programmers.co.kr/learn/courses/30/lessons/77484#fnref1)
- 플랫폼: 프로그래머스
- 풀이에 걸린 시간: 20분
문제를 읽고, 단순 구현문제임을 알았다. 당첨가능한 최저 순위는  있는 숫자에서의 당첨된 수, 최고 순위는 거기서 지워진 숫자수만큼 더하면 되겠다는 생각이 떠올랐고, 실제로 그대로 코드를 작성하니 통과가 됐다.
생각보다 빨리 풀려서, 원래는 리팩토링을 잘 안했는데, 이제부터 함수를 분리하는 습관을 가져보고자 책임별로 분리해봤다. 뭔가 최저, 최고 순위 카운팅하는 부분도 분리해야하나 고민이 들었지만, 그러다보면 뭔가 더 복잡한 코드가 될 것 같아서 냅뒀다.

solve: 로또의 최고 순위와 최저 순위

---

ChoYoonU/javascript/120822.js

- 문제:  120822: 문자열 뒤집기
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 12분
-  문자열을 split()메서드로 배열로 만든 뒤, reverse()메서드로 뒤집고, join()메서드로 다시 문자열로 합쳐 반환합니다.
- [MDN 공식문서](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/split#split%EC%9C%BC%EB%A1%9C_%EB%AC%B8%EC%9E%90%EC%97%B4_%EB%92%A4%EC%A7%91%EA%B8%B0)에서는 유니코드 문자를 제대로 처리하지 못하기 때문에 효과적인 방법은 아니라고 합니다.  
- 유니코드 문자를 포함한 문자열을 다룰 경우, Array.from() 또는 스프레드 연산자(...)를 사용하는 것이 적합합니다:

프로그래머스 #120822.문자열 뒤집기

---

KimJuWon/python/1차원 바람.py

- 문제: [1차원 바람](https://www.codetree.ai/missions/2/problems/The-1D-wind-blows?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 1시간 11분
- 완전 탐색
- Big-O 시간 : 바람이 특정행에서 시작하여 해당 행의 모든 열로 전달되고, 최악의 경우 배열의 전체 행으로 전달될 수 있다. 그리고 이러한 바람이 Q번 반복하므로 O(MNQ) 정도로 최적화할 수 있고, 각각이 100이하의 수이므로 문제에서 요구한 조건인 1초 내에 해결이 가능하다. 
- 문제의 조건을 정리하면 아래와 같다. 
- q번 바람이 주어지고, 바람의 시작되는 방향은 L또는 R로 주어지고, 시작되는 행의 번호가 r이 주어진다. 그리고 바람이 불개되면 바람의 시작되는 쪽부터 반대쪽으로 요소가 한칸씩 이동한다. 
- 이러한 한칸씩 요소가 이동(shift)가 되고 난뒤, 앞과 뒤 행을 비교했을 때 같은 열 번호에 똑같은 숫자가 있으면 바람이 전파된다. 이 때 바람의 방향은 반대로 불게된다. 
- 그리고 이러한 전파는 행의 끝(0,n-1)에 도달하거나, 같은 열번호에 동일한 숫자가 하나도 존재하지 않을 때 멈추게 된다. 
- 구현 : 먼저, for 루프를 통해 각 바람을 하나씩 처리합니다. 바람의 방향에 따라 시프트가 가능하도록 조건을 설정해 …

# 코드 트리 #1차원 바람

---

WongiRim/Kids With the Greatest Number of Candies.java

문제: [Kids With the Greatest Number of Candies](https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/?envType=study-plan-v2&envId=leetcode-75)
언어: java
요로콤

[java] Kids With the Greatest Number of Candies

---

RimWongi/Move Zeroes.java

문제: [Move Zeroes](https://leetcode.com/problems/move-zeroes/description/?envType=study-plan-v2&envId=leetcode-75)
언어: java
요로케

[java] Move Zeroes

---

Sanghee/javascript/크레인 인형뽑기 게임.js

- 문제: [크레인 인형뽑기 게임](https://school.programmers.co.kr/learn/courses/30/lessons/64061)
- 플랫폼: 프로그래머스
- 풀이에 걸린 시간: 40분(설계 10, 풀이 15, 리팩토링 15)
구현 + 스택 개념이 들어간 문제다. 종이에 제시된 board 배열을 크레인 모양(NxN)에 맞게 그려보니, moves에 따라 어떻게 각 열의 맨 위의 값을 가져올까 풀이 방법이 금방 떠오를 수 있었다. 
제한 범위가 높진 않아서 이중 for문으로 풀면 되겠다 싶었고, 배열 위치에 맞게 크레인 뽑는 아이템 위치를 지정했다. 뽑으면 해당 아이템 자리를 0으로 초기화해주고, 바구니에 push할때 최상단의 아이템과 중복되는지 확인 후, count를 올리고, 중복된 아이템을 제거하는 과정을 거쳤다.
중복된 아이템을 제거할땐 처음엔 pop을 두번 썼는데, splice가 더 깔끔한 것 같아서 수정했다.

solve: 크레인 인형뽑기 게임

---

RimWongi/Reverse Words in String.java

문제: [Reverse Words in String](https://leetcode.com/problems/reverse-words-in-a-string/description/?envType=study-plan-v2&envId=leetcode-75)
언어: java
----

[java] Reverse Words in String

---

RimWongi/Revers vowels of a string.java

문제: [Revers vowels of a string](https://leetcode.com/problems/reverse-vowels-of-a-string/?envType=study-plan-v2&envId=leetcode-75)
언어: java
---

[java] Revers vowels of a string

---

RimWongi/CanPlaceflowers.java

문제: [CanPlaceflowers](https://leetcode.com/problems/can-place-flowers/description/?envType=study-plan-v2&envId=leetcode-75)
언어: java
배열 순회

[java] CanPlaceflowers

---

RimWongi/java/Is subsequence.java

문제: [Is subsequence](https://leetcode.com/problems/is-subsequence/?envType=study-plan-v2&envId=leetcode-75)
언어: java
포인터

[java] Is subsequence

---

Nochi/javascript/좌표 압축.js

문제: [좌표 압축](https://www.acmicpc.net/submit/18870/87142437)
언어: javascript
유니크한 배열을 만든 뒤 정렬하고 처리함.

[javascript] 좌표 압축

---

KimJuWon/python/2D Wind.py

- 문제: [2D Wind](https://www.codetree.ai/missions/2/problems/The-2D-wind-blows?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 1시간 41분
- 문제 유형 : 완전탐색 
- Big-O 시간 복잡도 : 값을 순회하며 갱신을 여러번 해야하는 문제로, 처음에 바람이 전파되는 방향으로 각 격자에 있는 값을 순회하며 갱신해주고, 이후 이중 for루프를 돌며 각각 r1, r2 그리고 c1, c2 값 내부에 있는 값을 규칙에 맞게 갱신해줘야합니다. 이러한 작업은 격자 전체 크기인 n, m 만큼 q번이 최대 이루어질 수 있으므로 BigOt시간은 O(nmq)이며 1초 안에 해결이 가능합니다.

#코드 트리 2D wind

---

RimWongi/java/Two Sum.java

문제: [Two Sum](https://leetcode.com/problems/two-sum/)
언어: java
Map 사용

[java] Two Sum

---

ChoYoonU/javascript/120823.js

- 문제: [120823: 직각삼각형 출력하기](https://school.programmers.co.kr/learn/courses/30/lessons/120823)
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 1시간
- 풀이가 떠오른 과정: 문제를 읽고 시간제한과 메모리제한 내에서 해결이 가능한 지는 모르겠지만 풀이가 떠올랐다
- 풀이 작성 과정:  풀이를 남의 정답코드를 찾아 참고하여 작성하였다.
- 초기화 부터 readline이라는 모듈이 있어서 이게 맞나 싶어서 다른 언어의 초기화를 살펴 봤습니다.
- readline 모듈은 Node.js에서 제공하는 기본 모듈로, 입력 스트림(예: 사용자 입력)을 읽고 출력 스트림(예: 출력창)을 작성하는 데 사용됩니다. 주로 CLI(Command Line Interface) 환경에서 사용자와 상호작용할 때 사용됩니다.
- line.split(' ')으로 입력값을 배열로 분리하고, Number로 변환해 반복문에서 처리합니다.
- repeat() 메서드로를 이용해 * 문자를 반복하여 삼각형을 출력합니다.

프로그래머스 #120823.직각삼각형 출력하기

---

ChoYoonU/javascript/120824.js

- 문제: 120824: 짝수 홀수 개수(https://school.programmers.co.kr/learn/courses/30/lessons/120824)
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 38분
- a와 b를 각각 짝수와 홀수 개수를 저장하는 변수로 초기화합니다.
- 배열 num_list를 반복문으로 순회하며 짝수(num_list[i] % 2 === 0)면 a를 증가, 홀수면 b를 증가합니다.
- [a, b]를 배열로 반환합니다.
- reduce() 메서드를 사용하면 더 효욜적인 코드가 된다고 합니다.

프로그래머스 #120824.짝수 홀수 개수

---

Geunho/Python/LeetCode_2558.py

- 문제: [2558번: Take Gifts From the Richest Pile](https://leetcode.com/problems/take-gifts-from-the-richest-pile/)
- 언어: Python
- 풀이에 걸린 시간: 10분
- 풀이가 떠오른 과정: 예제 1번을 손으로 써가면서 정렬 또는 힙이 필요하다는 아이디어 캐치 후 구현
- 풀이 작성 과정: Python에는 max heap이 없으므로 음수로 변환 후 min heap을 활용해서 조건 구현 후 마지막에 다시 역산

LeetCode #2558

---

ChoYoonU/javascript/120825.js

- 문제: 120825번: 문자 반복 출력하기(https://school.programmers.co.kr/learn/courses/30/lessons/120825)
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 37분
- 문자열 my_string을 배열로 변환(...my_string)합니다.
- 반복문으로 배열을 순회하며, 각 문자에 대해 repeat(n) 메서드를 사용해 n번 반복된 값을 answer[i]에 저장합니다.
- 최종적으로 배열을 문자열로 병합(join(''))하여 반환합니다.
- 더 간결하고 효율적인 남의 코드는 아래와 같습니다.
```js
function solution(my_string, n) {
return [...my_string].map(char => char.repeat(n)).join('');
}
```

프로그래머스 #120825.문자 반복 출력하기

---

AnYuLim/Javascript/baek_17484_진우의 달 여행(Small).js

- 문제: [17484번: 진우의 달 여행 (Small)](https://www.acmicpc.net/problem/17484)
- 플랫폼: 백준 온라인 저지
- 풀이가 떠오른 과정: dfs?bfs? 생각하다가 패스해야하는 방향이 있어서 백트래킹으로 해야겠다 생각
- 풀이 작성 과정: 
백트래킹 함수를 재귀호출 할 때 현재 방향 정보를 인자로 보내서 그 방향을 제외 처리
모든 시작점 -> space[0]의 모든 원소를 스타트지점으로 M번 반복
종료조건 -> 행 인덱스가 N과 같을 때, 더해왔던 값을 전역 res변수에 min값으로 업데이트
1. 백트래킹
- 탐색 중 불필요한 경로는 굳이 끝까지 탐색하지 않겠다. => **가지치기**
2. DFS
- 가능한 모든 경로를 깊이 우선으로 탐색한다.
개념을 다시 생각해보니 제 풀이가 백트래킹이 아니라 그냥 DFS 같군요
가지치기 작업이 없고 모든 탐색을 진행했으니 ..? (가지치기 하면 틀린 답을 도출할 수 있음)
또한 패스하는 방향은 그냥 문제의 의도일 뿐 임의로 못 가는 길을 가지치기한게 아니지 않나 라는 생각이 듦
리뷰로 어떤 걸 요청해야 할 지 모르겠어요! 봐주신다면 감사드리고 뭐든 다 좋아요!!
더 나은 방법이라던가 팁이 혹시 있다면 마구마구 부탁드려요.🙇🏻‍♀️

241212 / 백준 / 17484 / javascript

---

AnYuLim/Javascript/prog_할인 행사.js

- 문제: [할인 행사](https://school.programmers.co.kr/learn/courses/30/lessons/131127)
- 플랫폼: 프로그래머스
- 언어: 자바스크립트
- 풀이에 걸린 시간: 21분
- 풀이가 떠오른 과정: 완탐..
- 풀이 작성 과정: 그냥 .. 완탐 ...
for문의 범위 -1 실수해서 디버깅 시간 조금 걸렸음

241214 programmers 할인 행사

---

Juwan/python/에어컨.py

- 문제: [프로그래머스 #214289 에어컨](https://school.programmers.co.kr/learn/courses/30/lessons/214289)
- 플랫폼: 프로그래머스
- 언어: python
- 풀이가 떠오른 과정: 문제를 읽고 풀이가 떠오르지 않았다.
- 풀이 작성 과정: 2차원 dp테이블을 사용한다는 것을 참고한 후 작성하였다.
- dp[i][j] → i분에 j + 10도를 만들 수 있는 가장 적은 전력으로 두고 풀이
- dp[0][temperature] = 0 으로 초기화 한 다음, 온도 변화 경우의 수 6가지에 대해 dp 테이블 갱신

프로그래머스 #214289 에어컨 (python)

---

ChoYoonU/javascript/120829.js

- 문제: 120829번: [각도기](https://school.programmers.co.kr/learn/courses/30/lessons/120829)
- 플랫폼: 프로그래머스
- 언어: js
- 풀이에 걸린 시간: 10분
- if 조건문으로 각도 angle의 값을 확인하여 평각, 둔각, 직각, 예각에 따라 answer 값을 설정합니다.
- 각 조건이 만족되면 해당 값을 반환(return)합니다.

프로그래머스 #120829.각도기

---

KimDaeho/Python/LeetCode_128_Longest_Consecutive.py

- 문제: [128번: Longest Consecutive Sequence](https://leetcode.com/problems/longest-consecutive-sequence/)
- 언어: python
- 풀이에 걸린 시간: 1시간
- 풀이가 떠오른 과정: 
1. 가장 긴 연속된 배열을 구성해야 하는데, 시간 복잡도 제한이 O(N)인 것을 확인.
2. 정렬로는 O(NlogN)이 최선이라고 생각하여 알고리즘이 아닌 자료구조를 통한 풀이로 접근해야 한다고 생각함.
3. 양방향 연결 리스트를 구성하면 O(N)으로 해결할 수 있을 것으로 생각함.
- 풀이 작성 과정: 
1. 주어진 배열을 순환하면서 부모 자식으로 연결된 양방향 연결 리스트를 구성(부모가 없으면 head, 자식이 없으면 tail)
2. 배열을 한 번 더 순회하면서, 가장 긴 길이의 리스트를 가지는 head 노드를 탐색
- 자료구조
- 양방향 연결 리스트

[Python] LeetCode 128. Longest Consecutive

---

KimDaeho/Python/LeetCode_198_House_Robber.py

- 문제: [198번: House Robber](https://leetcode.com/problems/house-robber/description/)
- 언어: python
- 풀이에 걸린 시간: 1시간
- 풀이가 떠오른 과정: 
[틀린풀이]
1. Greedy 풀이로 가장 점수가 높은 순서대로 선택하면 될 줄 알았음.
2. `[2, 3, 2]` 반례에 막혀서 틀림
[정답풀이]
1. 입력 배열의 길이가 최대 100밖에 안되니까 메모이제이션을 활용하면 어떨까 고민해 봄. (DP 풀이)
- 풀이 작성 과정: 
1. 리스트를 순회하면서 DP 리스트에 "현재 원소까지 탐색 했을 때의 최대 값"을 저장한다.
2. 아래의 규칙으로 N번째 DP 원소(`DP(N)`)를 계산한다.
- 현재 원소를 선택하고 `DP(N-2)`와 합친다.
- 혹은, 현재 원소를 포기하고, `DP(N-1)`을 선택한다.
- 메모이제이션
- DP

[Python] LeetCode 198. House Robber

---

ChoiSoYeong/javascript/42578.js
ChoiSoYeong/javascript/72411.js

- 문제1: [72411-메뉴 리뉴얼](https://school.programmers.co.kr/learn/courses/30/lessons/72411)
- 문제2: [42578-의상](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
- 플랫폼: 프로그래머스
- 풀이에 걸린 시간: 2시간 / 1시간
- 풀이가 떠오른 과정: 
- 72411: 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.
- 42578: 풀이를 아무런 도움 없이 작성하였다. -> 한번 틀려서 풀이를 한번 보고 이해했다.
- 풀이 작성 과정: 해시를 이용해 풀었다.

programmers #72411 #42578

---

RImWongi/java/test s.java

문제: [test s](https://leetcode.com/problems/two-sum/)
언어: java

[java] test s

---

RimWongi/java/Nearest Exit from Entrance in Maze.java

문제: [Nearest Exit from Entrance in Maze](https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/description/?envType=study-plan-v2&envId=leetcode-75)
언어: java

[java] Nearest Exit from Entrance in Maze

---

ParkJiHan/python/Who is in the middle?.py

문제: [Who is in the middle?](https://www.acmicpc.net/problem/6840)
언어: python
python list 정렬을 활용해서 중간값을 찾는 방식으로 작성해봤어요.

[python] Who is in the middle?

---

DoyulKim/java/1792. Maximum Average Pass Ratio.java

문제: [1792. Maximum Average Pass Ratio](https://leetcode.com/problems/maximum-average-pass-ratio)
언어: java
- Priority Queue
- Greedy
- Math
1. 각 클래스의 증가량((pass+1)/(total+1) - pass/total)을 계산
2. PriorityQueue를 사용하여 증가량이 가장 큰 클래스부터 처리
3. extraStudents만큼 반복하면서 학생 배정
4. 최종 평균 합격률 계산
- 시간 복잡도: O(E * logN), 여기서 E는 extraStudents, N은 classes의 길이
- 공간 복잡도: O(N), PriorityQueue를 위한 공간
1. PriorityQueue를 사용한 Greedy 알고리즘 구현 방법
2. 증가량 기반의 우선순위 결정 방법

[java] 1792. Maximum Average Pass Ratio

---

yoonucho/javascript/양꼬치.js

문제: [양꼬치](https://school.programmers.co.kr/learn/courses/30/lessons/120830)
언어: javascript
기본 비용은 n * 12000 + k * 2000으로 계산합니다.
10인분 이상 주문 시, 10인분당 음료 1잔 무료 혜택이 있으므로, Math.trunc(n / 10) * 2000만큼 할인합니다.

[javascript] 양꼬치

---

ChoYoonU/javascript/프로그래머스 #120830.양꼬치.js

문제: [프로그래머스 #120830.양꼬치](https://school.programmers.co.kr/learn/courses/30/lessons/120830)
언어: javascript
기본 비용은 n * 12000 + k * 2000으로 계산합니다.
10인분 이상 주문 시, 10인분당 음료 1잔 무료 혜택이 있으므로, Math.trunc(n / 10) * 2000만큼 할인합니다.

[javascript] 프로그래머스 #120830.양꼬치

---

DoyulKim/java/3239. Minimum Number of Flips to Make Binary Grid Palindromic I.java

문제: [3239. Minimum Number of Flips to Make Binary Grid Palindromic I](https://leetcode.com/problems/minimum-number-of-flips-to-make-binary-grid-palindromic-i)
언어: java
- 구현
- 배열
- Two Pointer
- Greedy
1. Row와 Column 각각의 관점에서 palindrome을 만들기 위한 최소 flip 횟수를 계산
2. Two pointer 방식으로 양 끝에서부터 비교하며 다른 값이 있을 때마다 flip 카운트
3. Row와 Column 방향의 flip 횟수 중 최소값을 반환
4. Edge case (m=1 또는 n=1)의 경우 항상 0을 반환
- 시간 복잡도: O(m*n)
- 각 row와 column을 한 번씩 순회
- 공간 복잡도: O(max(m,n))
- column 처리를 위한 임시 배열 필요 - 필수는 아님

[java] 3239. Minimum Number of Flips to Make Binary Grid Palindromic I

---

Sanghee/javascript/소수 만들기.js
sanghee/javascript/소수 만들기.js

문제: [소수 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12977)
언어: javascript
주어진 숫자중 3개의 숫자만 더하고, 숫자 개수도 3~50개밖에 안돼서 삼중 for문으로 풀었다.

[javascript] 소수 만들기

---

RimWongi/java/Donut and bar graph.java

문제: [Donut and bar graph](https://school.programmers.co.kr/learn/courses/30/lessons/258711)
언어: java

[java] Donut and bar graph

---

ChoYoonU/javascript/프로그래머스 #120831.짝수의 합.js

문제: [프로그래머스 #120831.짝수의 합](https://school.programmers.co.kr/learn/courses/30/lessons/120831)
언어: javascript
- 1부터 n 이하의 모든 짝수를 더하기 위해서 for문을 사용해서 2부터 시작해 2씩 증가시키며 answer에 더합니다.

[javascript] 프로그래머스 #120831.짝수의 합

---

programmers #42861 #섬 연결하기/java/programmers #42861 #섬 연결하기.java

문제: [programmers #42861 #섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
언어: java
E 가 간선의 개수일 때, O(ElogE) 의 시간복잡도를 가지는 크루스칼 알고리즘을 활용하는 문제입니다.
이 알고리즘에서 가장 시간이 오래 걸리는 작업은 간선의 cost 를 기준으로 오름차순으로 정렬할 때 입니다.
근데 문제에서 N 이 최대 100개 라고 주어져서 굳이 크루스칼 알고리즘을 사용하지 않고, 다른 그래프 알고리즘이나 완전탐색을 사용해도 될 것 같아요.

[java] programmers #42861 #섬 연결하기

---

Nochi/javascript/2635. Apply Transform Over Each Element in Array.js

문제: [2635. Apply Transform Over Each Element in Array](https://leetcode.com/problems/apply-transform-over-each-element-in-array/)
언어: javascript

[javascript] 2635. Apply Transform Over Each Element in Array

---

ParkJiHan/python/Julka.py

문제: [Julka](https://www.acmicpc.net/problem/8437)
언어: python

[python] Julka

---

KimJuWon/python/기울어진 직사각형의 회전.py

문제: [기울어진 직사각형의 회전](https://www.codetree.ai/missions/2/problems/rotate-slanted-rectangle?&utm_source=clipboard&utm_medium=text)
언어: python
시뮬레이션 문제로, 마름모 방향으로 값들을 한칸씩 shift해주도록 코드를 구현해주었습니다. Big-O시간은 마름모 최대 길이인 O( √n)입니다.

[python] 기울어진 직사각형의 회전

---

ParkJiHan/python/Zadanie próbne.py

문제: [Zadanie próbne](https://www.acmicpc.net/problem/8545)
언어: python

[python] Zadanie próbne

---

ParkJiHan/python/Disastrous Doubling.py

문제: [Disastrous Doubling](https://www.acmicpc.net/problem/14991)
언어: python
O(N)
```python
n = int(input())
bs = list(map(int,input().split()))
a = 1
MOD = 1000000007
for b in bs:
a = ( a * 2 ) - b
if a < 0:
print('error')
break
if a > MOD:
a %= MOD
else:
print(a)
```
왜 이런 모양으로 For문 안에서 모듈러 연산을 하면 틀릴까요?

[python] Disastrous Doubling

---

ChoYoonU/javascript/프로그래머스 #120833.배열 자르기.js

문제: [프로그래머스 #120833.배열 자르기](https://school.programmers.co.kr/learn/courses/30/lessons/120833)
언어: javascript
- slice(num1, num2 + 1) 메서드를 사용해 원하는 범위를 추출합니다. num2 + 1은 종료 인덱스(end)가 포함되지 않기 때문에, num2번 인덱스까지 포함하려면 필요합니다.

[javascript] 프로그래머스 #120833.배열 자르기

---

Geunho/Python/LeetCode_1475.py

- 문제: [1475번: Final Prices With a Special Discount in a Shop](https://leetcode.com/problems/final-prices-with-a-special-discount-in-a-shop/)
- 언어: Python
- 풀이에 걸린 시간: 30분
- 풀이가 떠오른 과정: 문제 조건이 여유가 있어서 처음에는 브루트포스 (N^2)로 접근해서 풀이. 이후 단조 스택을 활용해서 선형시간 복잡도로 개선
- 풀이 작성 과정: 단조 스택을 활용하여 Next Smaller Element를 계산 할 수 있고, 그걸 활용하여 할인된 가격 계산

LeetCode #1475

---

KimJuWon/python/최단 Run Length 인코딩.py

- 문제: [최단 Run Length 인코딩](https://www.codetree.ai/missions/2/problems/shortest-run-length-encoding?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 18분
- 시뮬레이션 문제로 문자열을 한방향씩 시프트하며, 문제에 있는 압축 규칙에 따라 문자열  만들고 이 때, 가장 작은 문자열의 길이를 문제입니다. for루프와 인덱싱을 이용해 Shift연산을 진행하고, 해당 연산이 진행될 때마다 문자열을 압축해 길이를 측정하여 최소인 길이를 측정합니다. Big-O시간은 문자의 길이만큼 이중 for루프를 순회하기 때문에 O(n^2)입니다.

add source code KimJuWon/Python/최단 Run Length 인코딩.py 20241218

---

KimJuWon/python/1차원 젠가.py

- 문제: [1차원 젠가](https://www.codetree.ai/missions/2/problems/jenga-1d?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 22분
- 시뮬레이션 문제로 문자열을 한방향씩 문제에 조건에 맞게 블록들을 2번 삭제 해주는 문제입니다. 두개의 배열을 선언하여 한 배열에서 순회하며 남아있는 배열들을 체크하고 하고 이동시킨 뒤, 삭제를 반복하는 방식으로 구현해주었습니다.

#코드 트리 #1차원 젠가

---

programmers #49189/java/programmers 가장 먼 노드.java

문제: [programmers 가장 먼 노드](https://school.programmers.co.kr/learn/courses/30/lessons/49189)
언어: java
bfs 문제

[java] programmers 가장 먼 노드

---

kimjuwon/python/십자 모양 폭발.py

문제: [십자 모양 폭발](https://www.codetree.ai/missions/2/problems/cross-shape-bomb?&utm_source=clipboard&utm_medium=text)
언어: python
그리드를 완전탐색하며 폭발이 일어나지 않은 값들을 문제의 규칙에 맞게 가장 낮은 행부터 차례대로 그리드 값을 갱신해주었습니다. 문제는 그리드를 완전탐색했기 때문에 시간 복잡도는 O(n^2)으로 해결할 수 있었습니다.

[python] 십자 모양 폭발

---

choyoonu/javascript/프로그래머스 #120834. 외계행성의 나이.js

문제: [프로그래머스 #120834. 외계행성의 나이](https://school.programmers.co.kr/learn/courses/30/lessons/120834)
언어: javascript
- for문을 사용해 ASCII 코드 97('a')부터 106('j')까지의 문자를 alphabet 배열에 저장합니다.
- age를 문자열로 변환하고, 각 숫자를 split() 메서드로 나눈 뒤 map() 메서드로 해당 숫자에 맞는 알파벳으로 변환합니다.
- 변환된 알파벳 배열을 join('') 메서드로 합쳐 문자열로 반환합니다.

[javascript] 프로그래머스 #120834. 외계행성의 나이

---

programmers #64062/java/programmers #64062 #징검다리 건너기.java

문제: [programmers #64062 #징검다리 건너기](https://school.programmers.co.kr/learn/courses/30/lessons/64062)
언어: java
배열의 크기가 20만, 배열의 각 원소들의 값이 2억 이어서 O(logN) 알고리즘인 이분 탐색 알고리즘을 떠올렸지만, 어떻게 적용할지 몰라서 헤맸습니다.
잊고 있었던 파라메트릭 서치(Parametric Search) 개념을 상기시켜서 문제를 풀었습니다.
소요 시간: 1시간 30분

[java] programmers #64062 #징검다리 건너기

---

doyulkim/java/769. Max Chunks To Make Sorted.java

문제: [769. Max Chunks To Make Sorted](https://leetcode.com/problems/max-chunks-to-make-sorted)
언어: java
chunk로 나눴을 때 chunk에서의 최대값과 배열 index 를 비교하는 로직이었습니다..

[java] 769. Max Chunks To Make Sorted

---

yoonucho/javascript/양꼬치.js

알고풀이로 작성하는 과정에서 초반에 영문 이름을 기존과 다른 이름으로 작성해 불필요한 디렉토리가 생성되었습니다. 이를 삭제하고 싶습니다.

Delete yoonucho/javascript directory

---

rimwongi/java/canplaceflowers_2052_2052.java

문제: [Can Place Flowers](https://leetcode.com/problems/can-place-flowers/description/?envType=study-plan-v2&envId=leetcode-75)
언어: java

[java] canplaceflowers_2052

---

Sanghee/javascript/최솟값 만들기.js
sanghee/javascript/최솟값만들기_2107_2108.js

문제: [최솟값 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12941)
언어: javascript
길이가 같은 배열에서 선택되지 않은 인자들 간의 곱의 최솟값을 구하는 문제였습니다. 이는 현 시점 가장 최솟값 x 최댓값을 곱하면 최솟값이 나옴을 인지했습니다. 그래서 한 배열은 오름차순, 다른 배열은 내림차순으로 정렬하여, for문으로 같은 인덱스별로 곱해서 더하도록 했습니다

[javascript] 최솟값만들기_2107

---

rimwongi/java/issubsequence_2121.java

문제: [Is Subsequence](https://leetcode.com/problems/is-subsequence/?envType=study-plan-v2&envId=leetcode-75)
언어: java

[java] issubsequence

---

jinlee/javascript/돌게임3_1458.js

문제: [돌 게임 3](https://www.acmicpc.net/problem/9657)
언어: javascript

[javascript] 돌게임3

---

choyoonu/javascript/프로그래머스#120835진료순서정하기_1549.js

문제: [프로그래머스 #120835 진료순서 정하기](https://school.programmers.co.kr/learn/courses/30/lessons/120835)
언어: javascript
- emergency 배열의 복사본을 생성하고, 내림차순으로 정렬해 sorted에 저장합니다.
- 원래 배열 emergency를 map() 메서드로 순회하며, 각 값이 정렬된 배열 sorted에서 몇 번째 인덱스인지 찾고(indexOf), 순위를 계산합니다.

[javascript] 프로그래머스#120835진료순서정하기

---

Sanghee/javascript/완주하지 못한 선수.js
sanghee/javascript/완주하지못한선수_1655.js

문제: [완주하지 못한 선수](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
언어: javascript
참가자를 hash map에 순차적으로 넣으면서 카운트를 증가시키고, 도착자를 순차적으로 카운트를 감소시켜 미완주자를 찾아냈습니다.

[javascript] 완주하지못한선수

---

Geunho/Python/LeetCode_2415.py

- 문제: [2415번: Reverse Odd Levels of Binary Tree](https://leetcode.com/problems/reverse-odd-levels-of-binary-tree)
- 언어: Python
- 풀이에 걸린 시간: 30분
- 풀이가 떠오른 과정: 문제를 잘못 이해해서 후위 순회 방식으로 구현하다가 트리 레벨이 홀수인 경우 완전히 뒤집어야한다는 것을 캐치, 따라서 BFS 방식으로 레벨에 따라 미리 순방향/역방향 처리를 저장해두고 트리를 만들어서 반환
- 풀이 작성 과정: 
- BFS를 활용해서 노드를 순회, 이 때 레벨 -> 노드 구조의 dict를 만들고 level이 홀수/짝수에 따라 역방향/순방향으로 저장
- 사전을 다 만든 후 리프 노드에서부터 역으로 상위 노드의 left, right를 연결

LeetCode #2415

---

nochi/javascript/2665.counterii_2300.js

문제: [2665. Counter II](https://leetcode.com/problems/counter-ii/description/)
언어: javascript

[javascript] 2665.counterii

---

choyoonu/javascript/프로그래머스#120836.순서쌍의개수_1455.js

문제: [프로그래머스#120836.순서쌍의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/120836)
언어: javascript
- 1부터 n까지 반복하며, n을 나눴을 때 나머지가 0인 경우 resultN을 증가시킵니다.
- resultN 값을 answer에 저장합니다.

[javascript] 프로그래머스#120836.순서쌍의개수

---

nochi/javascript/2666.allowonefunctioncall_2226.js

문제: [2666. Allow One Function Call](https://leetcode.com/problems/allow-one-function-call/description/)
언어: javascript

[javascript] 2666.allowonefunctioncall

---

kimjuwon/python/1차원폭발게임_2347.py

문제: [1차원 폭발 게임](https://www.codetree.ai/missions/2/problems/The-1D-bomb-game?&utm_source=clipboard&utm_medium=text)
언어: python
문제 설명:
주어진 배열에서 m개 이상 연속된 숫자가 있을 경우, 해당 숫자들을 배열에서 제거하는 문제입니다.
핵심 조건:
• 숫자를 제거한 후에도 m개 이상 연속된 숫자가 남아 있다면, 이를 반복적으로 제거해야 합니다.
• 배열에 연속된 숫자가 m개 미만이 될 때까지 이 과정을 반복합니다.
구현 방법:
배열을 순회하면서 제거해야 할 원소들의 인덱스를 set에 저장합니다. 이후, set에 포함되지 않은 원소들만 임시 배열(temp)에 추가하는 과정을 반복하여 연속된 숫자가 m개 이상 나오지 않도록 구현했습니다.

[python] 1차원폭발게임

---

choyoonu/javascript/프로그래머스_120837.개미군단_1544.js

문제: [프로그래머스_120837.개미 군단](https://school.programmers.co.kr/learn/courses/30/lessons/120837)
언어: javascript
- 체력을 장군개미(a = 5)로 나눈 몫을 answer1에 저장하고, 나머지를 병정개미(b = 3)로 나눈 몫을 answer2에 저장합니다.
- 병정개미로 처리한 후의 나머지를 그대로 일개미(c = 1)로 처리하여 answer3에 저장합니다.
- 총 병력 수는 answer1 + answer2 + answer3의 합으로 계산됩니다.

[javascript] 프로그래머스_120837.개미군단

---

minjiwoo/letter-combinatinos-of-a-phone-number.py

> ‼️ 예시 PR 템플릿입니다. 꼭 양식에 맞출 필요는 없습니다. 본인의 템플릿을 가져다 쓰거나, 작성이 번거롭다고 느낄 경우 작성하지 않고 PR을 생성하셔도 무방합니다. 단, 문제의 출처는 작성해주시기 바랍니다.
> 
> PR 템플릿이 길어서 슬랙 메시지가 세로로 너무 길어지네요..! 본인이 체크한 항목 이외의 것들은 지워주세요!
- 문제: [0000번: name](https://www.acmicpc.net/problem/0000)
- 플랫폼: 백준 온라인 저지
- 언어: python
- 풀이에 걸린 시간: 20분
- 풀이가 떠오른 과정: 알파벳 순열을 만든다는 점에서 -> 백트래킹 알고리즘이 떠오름 
- 풀이 작성 과정: 
> # 예시
> 예시입니다. 아래는 전부 지우고 제출해주세요 :)
> - 문제: [0000번: name](https://www.acmicpc.net/problem/0000)
> - 플랫폼: 백준 온라인 저지
> - 언어: python
> - 풀이에 걸린 시간: 2시간
>   
> - 풀이가 떠오른 과정: 문제를 읽고 주어진 시간제한과 메모리제한 내에서의 풀이가 떠올랐다.
> - 풀이가 떠오른 과정: 문제를 읽고 시간제한과 메모리제한 내에서 해결이 가능한 지는 모르겠지만 풀이가 떠올랐다.
> - 풀이가 떠오른 과정: 문제를 읽고 풀이가 떠오르지 않았다.
> - 풀이가 떠오른 과정: 문제가 곧바로 이해되지 않았다.
>
> - 풀이 작성 과정: 풀이를 아무런 도움 없이 작성하였다.
> - 풀이 작성 과정: 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.
> - 풀이 작성 …

LeetCode letter-combinations-of-a-phone-number

---

nochi/javascript/2667.createhelloworldfunction_1833.js

문제: [2667. Create Hello World Function](https://leetcode.com/problems/create-hello-world-function/description/)
언어: javascript

[javascript] 2667.createhelloworldfunction

---

parkjihan/python/[2744]대소문자_바꾸기_1333.py

문제: [[2744]대소문자_바꾸기](https://www.acmicpc.net/problem/2744)
언어: python
파이썬 str 자체메서드를 활용해봤습니다.

[python] [2744]대소문자_바꾸기

---

choyoonu/javascript/프로그래머스_120838.모스부호(1)_1556.js

문제: [프로그래머스_120838.모스부호(1)](https://school.programmers.co.kr/learn/courses/30/lessons/120838)
언어: javascript
- letter 문자열을 공백으로 분리하여 모스부호 배열(splitLetter)로 만듭니다.
- 각 모스부호를 morse 객체를 이용해 알파벳으로 매핑하고 , 변환된 알파벳을 하나의 문자열로 결합합니다.

[javascript] 프로그래머스_120838.모스부호(1)

---

leehyunggeol/java/programmers#42627#디스크컨트롤러_1954.java

문제: [programmers #42627 #디스크 컨트롤러](https://school.programmers.co.kr/learn/courses/30/lessons/42627)
언어: java
풀이 시간: 2시간
PriorityQueue 가 비어있을 때와 jobs 배열의 끝에 도달했을 때를 탈출 조건문으로 해야하고 각 job 의 시작시간과 총 걸린 시간을 유의해서 다루어야 한다.

[java] programmers#42627#디스크컨트롤러

---

nochi/javascript/2677.chunkarray_2341.js

문제: [2677. Chunk Array](https://leetcode.com/problems/chunk-array/description/)
언어: javascript

[javascript] 2677.chunkarray

---

rimwongi/java/prob3776_0010.java

문제: [Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/)
언어: java

[java] prob3776_0010

---

choyoonu/javascript/prob120839_1805.js

문제: [프로그래머스 #가위 바위 보_120839](https://school.programmers.co.kr/learn/courses/30/lessons/120839)
언어: javascript

[javascript] prob120839_1805

---

nochi/javascript/prob2695_1912.js

문제: [2695. Array Wrapper](https://leetcode.com/problems/array-wrapper/description/)
언어: javascript

[javascript] prob2695_1912

---

leehyunggeol/java/prob67259_2110.java

문제: [programmers #67259 #경주로 건설](https://school.programmers.co.kr/learn/courses/30/lessons/67259)
언어: java
조금 복잡한 bfs 문제이다.
4가지 방향(상,하,좌,우)별로 최솟값이 계속 달라질 수 있기 때문에 이를 모두 기록해주어야 한다. 
이것을 구현할 때 boolean[N][M][4] 의 visited 배열로 할지, int[N][M][4] 의 dp 배열로 할지는 푸는 사람의 마음이다.
다만, visited 배열로 할 때는 조건문에 주의해야 한다.
예를 들어, 
if (!visited[nx][ny][nDir] || newCost <= dp[nx][ny]) 
이 조건문에서 || 대신에 && 를 사용하면 안된다.
해당 셀을 방문했을 때, 똑같은 방향으로 방문하더라도 이전에 어떤 방향으로 다른 셀들을 방문했을지 모르기 때문에 어떤 방향이 최솟값이 될지 모르기 때문이다.

[java] prob67259_2110

---

kimjuwon/python/prob2048_2321.py

문제: [단 한 번의 2048 시도](https://www.codetree.ai/missions/2/problems/one-trial-of-2048-game?&utm_source=clipboard&utm_medium=text)
언어: python
4*4 격자안에서 2048 게임을 구현하는 것으로 시뮬레이션 문제에 해당합니다. 상, 하, 좌, 우로 모든 숫자가 이동하고, 겹치는 숫자가 있을 때는 값이 더해지도록 구현을 합니다. 문제 조건에 맞춰서 분기를 할 경우 상수시간안에 해결이 가능합니다. (O(1))

[python] prob2048_2321

---

choyoonu/javascript/prob120840_1554.js

문제: [프로그래머스 #120840. 구슬을 나누는 경우의 수](https://school.programmers.co.kr/learn/courses/30/lessons/120840)
언어: javascript
- 팩토리얼을 계산하는 재귀 함수를 작성하고, 값이 커질 것을 대비해 BigInt를 사용합니다.
- 조합 공식을 적용하여 n! / (n-m)! * m!을 계산합니다.
- 최종 결과를 Number로 변환해 반환합니다.

[javascript] prob120840_1554

---

jinlee/javascript/prob0650_1815.js

문제: [불](https://www.acmicpc.net/problem/5427)
언어: javascript

[javascript] prob0650_1815

---

src/main/java/LeeHyungGeol/java/programmers/베스트앨범/Solution.java
src/main/java/LeeHyungGeol/java/programmers/불량사용자/Solution.java
src/main/java/LeeHyungGeol/java/programmers/여행경로/Solution.java

- 문제 1: [42579번: 베스트앨범](https://school.programmers.co.kr/learn/courses/30/lessons/42579)
- 문제 2: [64064번: 불량 사용자](https://school.programmers.co.kr/learn/courses/30/lessons/64064)
- 플랫폼: 프로그래머스
- 언어: java
- 풀이에 걸린 시간: 1시간/45분
- 풀이 작성 과정: 
- 42579번: 베스트앨범: Hash 와 정렬을 이용하는 문제
- 64064번: 불량 사용자: 완전탐색 + 백트랙킹 문제인걸 알고, 바로 풀이를 작성했다. 
- 42579번: 베스트앨범: 중간에 가장 많이 플레이된 곡을 기준으로 정렬하기 위해 Map 의 데이터들을 List 에 옮긴 후, 다시 정렬하는 부분이 있는데 해당 부분을 좀 더 깔끔하게 하는 방법이 없을까 고민입니다.
- 64064번: [아이디들이 나열된 순서와 관계없이 아이디 목록의 내용이 동일하다면 같은 것으로 처리] 해당 내용을 처리하는데 있어서 String.split() 을 사용해서 정렬(Arrays.sort()) 후 다시 String.join() 을 이용하여 정답을 구했는데, 해당 과정이 생각보다 지저분하다고 생각해서 보다 코드를 깔끔하게 하는 방법이 없을까 고민입니다.

programmers #베스트앨범(42579) #불량사용자(64064)

---

rimwongi/java/prob4124_2229.java

문제: [Merge Strings Alternately](https://leetcode.com/problems/merge-strings-alternately/?envType=study-plan-v2&envId=leetcode-75)
언어: java

[java] prob4124_2229

---

nochi/javascript/prob2703_2358.js

문제: [2703. Return Length of Arguments Passed](https://leetcode.com/problems/return-length-of-arguments-passed/description/)
언어: javascript

[javascript] prob2703_2358

---

kimjuwon/python/십자 모양의 지속적 폭발.py

- 문제: [십자 모양의 지속적 폭발](https://www.codetree.ai/missions/2/problems/cross-shape-continuous-bomb?&utm_source=clipboard&utm_medium=text)
- 언어: python
- 풀이에 걸린 시간: 30분
- 시뮬레이션 문제로 문제에 제시된 대로 그리드 안에 있는 값들을 지정된 열에서 십자 형태로 삭제한다. 먼저, 지정된 열에서 십자 형태로 값을 삭제한 후, 남은 값들을 아래 방향으로 시프트한다. 이 과정은 마치 중력에 의해 값들이 떨어지는 모습과 유사하며, 숫자 값들 사이에 0이 끼지 않도록 조정해야 한다.시프트 작업은 임시 그리드(temp)를 활용하여 수행한다. 먼저 값을 temp에 옮긴 뒤, 이를 다시 원래 그리드로 이동시키는 방식으로 구현하였다. 이러한 연산은 폭탄의 횟수만큼 반복되며, 전체 시간복잡도는 O(n²m)이다.

십자 모양의 지속적 폭발 #CodeTree

---

leehyunggeol/java/prob132266_0048.java

문제: [programmers #132266 #부대복귀](https://school.programmers.co.kr/learn/courses/30/lessons/132266)
언어: java
bfs 문제입니다. 
간선 간의 cost 가 모두 1로 동일하고, 하나의 정점에서 다른 정점까지의 최단 거리를 구하는 문제여서 간단하게 bfs 알고리즘으로 문제를 풀 수 있습니다.
sources 길이만큼 bfs 알고리즘을 반복하는 것이 아닌, dist[N] 배열을 이용하여 각 source 에서 destination 까지 최단 거리를 저장해서 답을 구할 수 있습니다.

[java] prob132266_0048

---

simdongmin/java/prob1426_1220.java

문제: [Two Sum](https://leetcode.com/problems/two-sum/description/)
언어: java
배열의 두 요소을 더해 target 값이 되는 요소들의 위치를 반환하는 문제였습니다. 
이중 반복문을 돌면서 모든 조합을 찾는 방법도 있지만, map을 사용해서 (target-e) 값과 e값의 인덱스를 같이 저장해놓고 추후 (target-e) 를 순회할때, map에서 인덱스를 조회할 수 있게 한다면 더 적은 시간복잡도로 해결이 가능합니다.

[java] prob1426_1220

---

choyoonu/javascript/prob120841_1545.js

문제: [프로그래머스 #120841. 점의 위치 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/120841)
언어: javascript
- dot 배열에서 x와 y 좌표를 추출하여 각 사분면 조건에 따라 반환합니다.
- x와 y의 부호를 비교하여 1~4사분면 중 하나를 결정합니다.
- 조건문으로 사분면 번호(1~4)를 반환합니다.

[javascript] prob120841_1545

---

leehyunggeol/java/prob77486_1914.java

문제: [programmers #77486 #다단계 칫솔 판매](https://school.programmers.co.kr/learn/courses/30/lessons/77486)
언어: java
재귀(dfs) 및 hash 를 사용하는 문제였습니다.
문제가 길어서 무슨 말인지 이해를 처음에 잘 못했지만, 그림의 계산 과정만 잘 따라가보면 풀이는 그리 어렵지 않은 문제였습니다.
다만, 소수점 계산을 주의해야 하는 것과 아래로 내려갔을 때, amount == 0 이 될 때 return; 을 잘해줘야 시간 초과를 면할 수 있었습니다.
int rest = (int) (amount * 0.1); 
or 
int rest = amount / 10;

[java] prob77486_1914

---

jinlee/javascript/prob1317_1939.js

문제: [트리](https://www.acmicpc.net/problem/4803)
언어: javascript

[javascript] prob1317_1939

---

kimjuwon/python/prob2522_2208.py

문제: [최적의 십자 모양 폭발](https://www.codetree.ai/missions/2/problems/best-cross-shape-bomb?&utm_source=clipboard&utm_medium=text)
언어: python
- 문제 유형: 완전탐색 + 시뮬레이션
- 풀이 과정:
1. 전체 그리드를 하나씩 순회하면서, 해당 위치에 적힌 숫자 크기만큼 십자 모양으로 값을 제거합니다(0으로 표기).
2. 이후, 그리드 내에서 값이 0인 부분이 존재하지 않도록 아래 방향으로 값을 시프트합니다(중력 작용).
3. 다시 그리드를 순회하면서 각 요소의 상, 하, 좌, 우에 동일한 값이 있는지 확인하고, 그 개수를 세어줍니다.
4. 한 번의 폭발에서 가장 많이 카운트된 값을 답으로 갱신합니다.
- 주의할 점:
- 값이 중복으로 카운트되는 것을 방지하기 위해 최종 count 값에 2를 나눠줘야 합니다.
- 최초의 값을 보존하기 위해 임의의 그리드를 생성하여 작업을 수행합니다.
- 시간 복잡도:그리드 전체를 순회하며 폭발을 시뮬레이션하는 데 O(n²) 시간이 소요됩니다. 각 폭발마다 완전탐색과 count 계산이 필요하므로, 이 과정이 반복되어 최종적으로 O(n⁴)의 시간 복잡도가 발생합니다.

[python] prob2522_2208

---

rimwongi/java/prob8449_0013.java

문제: [광물캐기](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
언어: java

[java] prob8449_0013

---

jinlee/javascript/prob5566_1323.js

문제: [재귀함수가 뭔가요?](https://www.acmicpc.net/problem/17478)
언어: javascript

[javascript] prob5566_1323

---

jinlee/javascript/prob5516_1351.js

문제: [노드사이의 거리](https://www.acmicpc.net/problem/1240)
언어: javascript

[javascript] prob5516_1351

---

choyoonu/javascript/prob120842_1548.js

문제: [프로그래머스 #120842. 2차원으로 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/120842)
언어: javascript
- i를 n씩 증가시키며 num_list를 n개씩 잘라냅니다.
- num_list에서 현재 인덱스 i부터 i + n까지의 요소를 잘라 반환합니다.
- 잘라낸 배열을 answer배열에 추가하여 2차원 배열을 만듭니다.

[javascript] prob120842_1548

---

leehyunggeol/java/prob12907_2336.java

문제: [programmers #12907 #거스름돈](https://school.programmers.co.kr/learn/courses/30/lessons/12907?language=java)
언어: java
dp 문제입니다. 
DP의 핵심은 과거에 저장해둔 값을 바탕으로 현재 값을 도출해내는 것입니다.
그러므로 어떠한 의미있는 과거의 값을 저장해두고, 어떻게 현재 값을 도출하는데 과거의 값을 이용할 지를 생각해보고 점화식을 세워야 합니다.
이를 알기 위해서는 다음과 같은 방식으로 풀이를 진행해야 합니다.
1. 일정량의 데이터를 직접 손으로 작성해보기
2. 이전값들을 이용해서 현재 값을 구할 수 있는 방식을 찾아내기
3. 찾아낸 방식을 점화식으로써 코드에 적용하기
DP의 문제의 대부분은 막상 점화식으로 코드를 작성해보면 보통 짧고 단순하기 때문에, 2번이 핵심이라고 볼 수 있습니다.

[java] prob12907_2336

---

kimjuwon/python/prob2_0534.py

문제: [2차원 폭발게임](https://www.codetree.ai/missions/2/problems/The-2D-bomb-game?&utm_source=clipboard&utm_medium=text)
언어: python
2차원 폭발게임은 시뮬레이션 유형의 문제 풀이입니다. nXn 그리드가 주어지고, 열에 대해 행을 봤을 때 행에서 m개의 연속된 숫자들이 동시에 폭발하는데, 이 폭발은 m개이상 연속된 숫자들이 없을 때까지 반복됩니다. 그리고 중력이 작용하여 모든 리스트의 원소가 아래로 시프트되고, 90도 회전을 하는데 이러한 작업이 k번 반복됩니다. 
따라서 k번 만큼 작업을 반복할 수 있도록 for루프를 이용해 '연쇄적 폭발+중력 작용+90도 회전"을 반복할 수 있도록 합니다. 연쇄적 폭발은 각 열을 순서대로 순회하며 열에서 연속된 숫자가 있는지 탐색하고, m개 이상일 경우 값을 0으로 채웁니다. 그리고 이러한 작업은 폭발이 없을 때까지 반복합니다. 이후, 0이 이웃하지 않도록 아래로 시프트를 해주고, 90도를 회전합니다. 이 때, 작업을 용이하게 하기 위해 temp라는 임의의 배열을 선언하여 값을 옮기며 작업합니다. 최종적으로 마지막 90도 회전을 한 뒤, 마지막 연쇄적 폭발+중력 시프트 작업을 마무리 한뒤, 그리드 내에 0이 아닌 숫자값을 세주고 반환합니다.

[python] prob2_0534

---

juwan/python/prob76503_1028.py

문제: [프로그래머스 #76503 모두 0으로 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/76503)
언어: python

[python] prob76503_1028

---

choyoonu/javascript/prob120843_1443.js

문제: [프로그래머스 #120843. 공 던지기](https://school.programmers.co.kr/learn/courses/30/lessons/120843)
언어: javascript
- 공이  (1 + (k - 1) * 2) % numbers.length 위치로 이동하도록 계산합니다.
- 계산된 값을 그대로 반환하여 k번째 공을 받는 사람의 번호를 구합니다.
- 계산 결과가 0일 경우, 배열의 마지막 사람 번호를 반환합니다.

[javascript] prob120843_1443

---

jinlee/javascript/prob0115_1853.js

문제: [트리](https://www.acmicpc.net/problem/1068)
언어: javascript

[javascript] prob0115_1853

---

kimjuwon/python/prob8482_2328.py

문제: [숫자가 더 큰 인접한 곳으로 이동](https://www.codetree.ai/missions/2/problems/move-to-larger-adjacent-cell?&utm_source=clipboard&utm_medium=text)
언어: python
이 문제는 시뮬레이션 문제로, 그리드내에 행과 열 값이 주어지면 해당 위치로 부터 상,하,좌,우 방향에 큰 수가 있다면 이동하고, 방문한 그리드의 숫자 값을 기록하는 문제입니다. 문제의 조건에 맞게 이동할 수 있도록 상,하, 좌, 우 방향을 정의하고(dx, dy), for루프를 이용해 각 방향으로 갈 수 있는지 체크하며 이동이 가능하다면, 해당 위치로 이동하는 방식으로 구현해주었습니다. 최악의 경우는 그리드내에 모든 위치를 방문하는 것으로 O(n^2)이며, 주어진 시간 제한 내에 해결이 가능합니다.

[python] prob8482_2328

---

parkjihan/python/prob21598_0030.py

문제: [[21598]SciComLove](https://www.acmicpc.net/problem/21598)
언어: python

[python] prob21598_0030

---

choyoonu/javascript/prob120844_1554.js

문제: [프로그래머스 #120844. 배열 회전시키기](https://school.programmers.co.kr/learn/courses/30/lessons/120844)
언어: javascript
- direction == "left": 첫 번째 요소를 잘라 맨 뒤로 이동합니다.
- direction == "right": 마지막 요소를 잘라 맨 앞으로 이동합니다.
- slice()와 concat()을 사용해 배열을 재구성한 결과를 반환합니다.

[javascript] prob120844_1554

---

leehyunggeol/java/prob68646_1721.java

문제: [programmers #68646 #풍선터뜨리기](https://school.programmers.co.kr/learn/courses/30/lessons/68646)
언어: java
시뮬레이션 문제입니다. 천천히 규칙을 찾아야 합니다. 
원소가 3개일 때,
1,2,3 : 중간을 기준으로 한쪽이 크고, 한쪽이 작은 경우(오름차순)
3,2,1 : 중간을 기준으로 한쪽이 크고, 한쪽이 작은 경우(내림차순)
-1,2,1 : 중간을 기준으로 양쪽이 다 작은 경우
2,1,3 : 중간을 기준으로 앙쪽이 둘 다 큰 경우
위의 4가지 경우를 다 따져봐야 합니다.
중간을 기준으로 양쪽이 다 작은 경우, 즉 중간 값이 가장 큰 경우, 살아남을 수 없습니다.
임의의 수를 기준으로 왼쪽 배열의 최솟값 보다 크고, 오른쪽 배열의 최솟값 보다 크다면 끝까지 살아남을 수 없습니다.
따라서 맨 왼쪽을 뺸 오른쪽 배열의 최솟값 배열과 맨 오른쪽을 뺀 왼쪽 배열의 최솟값 배열의 2가지 배열이 필요합니다.

[java] prob68646_1721

---

leehyunggeol/java/prob49191_1722.java

문제: [programmers #49191 #순위](https://school.programmers.co.kr/learn/courses/30/lessons/49191)
언어: java
플로이드 워셜 문제입니다.

[java] prob49191_1722

---

nochi/javascript/prob2715_1804.js

문제: [2715. Timeout Cancellation](https://leetcode.com/problems/timeout-cancellation/description/)
언어: javascript

[javascript] prob2715_1804

---

kimjuwon/python/prob1_2326.py

문제: [떨어지는 1자 블록](https://www.codetree.ai/missions/2/problems/falling-horizontal-block?&utm_source=clipboard&utm_medium=text)
언어: python
떨어지는 1차 블록

[python] prob1_2326

---

nochi/javascript/prob2723_0047.js

문제: [2723. Add Two Promises](https://leetcode.com/problems/add-two-promises/description/)
언어: javascript

[javascript] prob2723_0047

---

nochi/javascript/prob2724_0115.js

문제: [2724. Sort By](https://leetcode.com/problems/sort-by/description/)
언어: javascript

[javascript] prob2724_0115

---

choyoonu/javascript/prob120845_1546.js

문제: [프로그래머스 #120845. 주사위의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/120845)
언어: javascript
- box 배열의 각 요소를 n으로 나눈 몫(Math.trunc)으로 변환합니다.
- 변환된 배열을 reduce() 메서드를 사용해 모든 요소를 곱합니다.
- 결과를 반환하여 box에 들어갈 수 있는 최대 개수를 계산합니다.

[javascript] prob120845_1546

---

leehyunggeol/java/prob133500_2035.java

문제: [programmers #133500 #등대](https://school.programmers.co.kr/learn/courses/30/lessons/133500)
언어: java
그래프의 특징을 이해하는 재밌는 문제였습니다.
dfs 를 이용하여 각 노드를 순회하며, 현재 노드의 자식 중 하나라도 꺼져있는 경우, 현재 노드의 불을 켠다.(isLightOn == 0  ->  return 1;) ( = 자식노드들이 모두 켜져있다면, 현재 등대는 키지 않아도 된다.)
리프 노드일 경우 부모 노드의 불을 무조건 켜야 한다. (return 1;)
return 1; => 부모 노드의 불을 켜야 한다.
return 0; => 부모 노드의 불을 안켜도 된다. 
O(N)

[java] prob133500_2035

---

leehyunggeol/java/prob152995_1510.java

문제: [programmers #152995 #인사고과](https://school.programmers.co.kr/learn/courses/30/lessons/152995)
언어: java
정렬과 그리디 문제입니다.
N 이 10만이기 때문에, 완전 탐색이 아닌 다른 방법을 생각해내야 했습니다.
우선순위큐 혹은 정렬을 사용해야 겠다고 생각했지만, 정렬 기준을 바로 생각해내지 못했습니다.
생각해보면 그리 어렵지 않은 문제이지만 살짝 쫄아서 문제를 제대로 파악하지 못했습니다.
하나는 내림차순, 나머지 하나는 오름차순으로 정렬을 해야 작은 값을 제외할 값을 구할 수 있습니다.
하나는 내림차순으로 정렬이 되어있기 때문에 값을 비교할 필요가 없고, 나머지 하나는 오름차순이기 때문에 max 값을 갱신해주다가 max 값 보다 낮다면 제외대상이기 때문에 -1 로 배열의 값을 갱신해준다.
그런 다음 scores 배열을 점수의 합 기준 내림차순으로 재정렬 해주면서 등수를 세주면 답을 구할 수 있다.

[java] prob152995_1510

---

choyoonu/javascript/prob120846_1720.js

문제: [프로그래머스 #120846. 합성수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/120846)
언어: javascript
- counts 배열을 초기화하고, 각 숫자 i의 배수를 탐색하여 해당 숫자의 약수 개수를 누적합니다.
- counts 배열에서 약수 개수가 3 이상인 숫자만 필터링하여 개수를 계산합니다.

[javascript] prob120846_1720

---

geunho/Python/LeetCode_1422.py

- 문제: [1422번: Maximum Score After Splitting a String](https://leetcode.com/problems/maximum-score-after-splitting-a-string/)
- 언어: Python
- 풀이에 걸린 시간: 10분
- 풀이가 떠오른 과정: 문제 조건 확인 후 요구사항대로 구현
- 풀이 작성 과정: 왼쪽 0의 갯수와 오른쪽 1의 갯수 관리할 변수 선언 후 슬라이딩하면서 갱신 및 정답 후보군 값 업데이트

LeetCode #1422

---

choyoonu/javascript/prob120847_1513.js

문제: [프로그래머스 #120847. 최댓값 만들기(1)](https://school.programmers.co.kr/learn/courses/30/lessons/120847)
언어: javascript
- 주어진 배열 numbers를 내림차순으로 정렬합니다.
- 정렬된 배열에서 가장 큰 값과 두 번째로 큰 값을 곱합니다.
- 곱한 결과를 반환합니다.

[javascript] prob120847_1513

---

leehyunggeol/java/prob92344_1649.java

문제: [programmers #92344 #파괴되지 않은 건물](https://school.programmers.co.kr/learn/courses/30/lessons/92344)
언어: java
prefix sum 즉, 누적합 개념을 사용하는 재밌는 문제였습니다.
2차원에서의 누적합 문제였습니다.
누적합에 대한 개념이 잘 나오지 않아서 희미 해졌는데, 이번에 다시 일깨우는 좋은 기회였습니다.

[java] prob92344_1649

---

minjiwoo/python/daily-temperatures.py

> ‼️ 예시 PR 템플릿입니다. 꼭 양식에 맞출 필요는 없습니다. 본인의 템플릿을 가져다 쓰거나, 작성이 번거롭다고 느낄 경우 작성하지 않고 PR을 생성하셔도 무방합니다. 단, 문제의 출처는 작성해주시기 바랍니다.
> 
> PR 템플릿이 길어서 슬랙 메시지가 세로로 너무 길어지네요..! 본인이 체크한 항목 이외의 것들은 지워주세요!
- 문제: [LeetCode: daily temperatures](https://leetcode.com/problems/daily-temperatures/)
- 플랫폼: leetcode
- 언어: python
- 풀이가 떠오른 과정: 
LeetCode 의 hint 를 참고 했다 -> stack 자료구조를 사용하라는 것. 자료구조를 떠올린 다음에 풀이를 생각할 수 있었다. 
- 풀이 작성 과정: 
temperature 배열을 선형 순회한다. 
현재 검사중인 tem (temperature[i]) 이 stack 의 top 보다 온도가 높으면, top 을 stack 에서 pop 한다. 
그리고 top 과 i 의 차이를 구해서 answer 배열에 저장한다. 
stack 에 값을 넣는다.

leetcode daily-temperatures.py

---

ChoiSoYeong/javascript/12985.js

- 문제: [12985]((https://school.programmers.co.kr/learn/courses/30/lessons/12985?language=javascript)
- 플랫폼: 프로그래머스
- 풀이에 걸린 시간: 40분
- 풀이 작성 과정: 풀이를 관련된 알고리즘 지식만을 찾아 숙지한 채 작성하였다.

programmers #12985
